name: Daily Robot Framework Tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Chrome for Testing
        run: |
          wget https://storage.googleapis.com/chrome-for-testing/latest/linux64/chrome-linux64.zip
          wget https://storage.googleapis.com/chrome-for-testing/latest/linux64/chromedriver-linux64.zip
          unzip chrome-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          echo "export PATH=/opt/chrome:$PATH" >> $GITHUB_ENV
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RF tests
        run: |
          mkdir -p results
          robot --pythonpath resources -d results tests/